import { Knex } from 'knex'

export async function seed(knex) {
  await knex('units').del()

  // Inserts CL units
  await knex('units').insert([
    // HQ
    {
      name: 'Crusader Clergy Team',
      faction: 'CL',
      category: 'HQ',
      points: 45,
      CC: 4,
      BS: 4,
      DE: 3,
      FW: 3,
      W: 6,
      WIP: 10,
      S: 2,
      MOV: '4-4',
      equipment: 'QBZ-110 Bullpup, Grenades',
      special_rules: 'Infantry, Fanatic',
    },

    // Troops
    {
      name: 'Crusader Rifle Team',
      faction: 'CL',
      category: 'Troop',
      points: 41,
      CC: 4,
      BS: 3,
      DE: 3,
      FW: 2,
      W: 5,
      WIP: 9,
      S: 2,
      MOV: '4-4',
      equipment: 'QBZ-110 Bullpup, Grenades',
      special_rules: 'Infantry, Fanatic',
    },
    {
      name: 'Crusader Specialist Team',
      faction: 'CL',
      category: 'Troop',
      points: 32,
      CC: 4,
      BS: 3,
      DE: 3,
      FW: 2,
      W: 3,
      WIP: 9,
      S: 2,
      MOV: '4-4',
      equipment: 'QBZ-110 Bullpup, Grenades',
      special_rules: 'Infantry, Fanatic',
    },

    // Elites
    {
      name: 'Crusader Zealot Team',
      faction: 'CL',
      category: 'Elite',
      points: 37,
      CC: 4,
      BS: 2,
      DE: 2,
      FW: 2,
      W: 5,
      WIP: 9,
      S: 2,
      MOV: '6-2',
      equipment: 'Heavy Pistols, Swords',
      special_rules: 'Infantry, Fanatic, Zealot, Infiltrator, Ambusher',
    },
    {
      name: 'Enhanced Crusader Team',
      faction: 'CL',
      category: 'Elite',
      points: 65,
      CC: 5,
      BS: 3,
      DE: 4,
      FW: 3,
      W: 6, // Cyborg equivalent → 2 wounds if you want
      WIP: 9,
      S: 3,
      MOV: '6-2',
      equipment: 'QBZ-110 Bullpup, Crusader Longswords',
      special_rules:
        'Infantry, Fanatic, Zealot, Hackable, Flurry Of Blades (2)',
    },
    {
      name: 'Assassin Team',
      faction: 'CL',
      category: 'Elite',
      points: 71,
      CC: 5,
      BS: 4,
      DE: 4,
      FW: 3,
      W: 3,
      WIP: 10,
      S: 2,
      MOV: '6-2',
      equipment: 'Heavy Pistols, Poison Daggers, Optical Camo',
      special_rules:
        'Infantry, Fanatic, Superior Infiltrators, Ambushers, Flurry Of Blades (4)',
    },

    // Drones
    {
      name: 'Tarantula Team',
      faction: 'CL',
      category: 'Drone',
      points: 39,
      CC: 4,
      BS: 2,
      DE: 3,
      FW: 3,
      W: 3,
      WIP: 10,
      S: 1,
      MOV: '4-4',
      equipment: 'Flamers, Drone Blades',
      special_rules: 'Drone, Infiltrator, Ambusher, Hackable',
    },
    {
      name: 'Locust Team',
      faction: 'CL',
      category: 'Drone',
      points: 27,
      CC: null,
      BS: null,
      DE: 2,
      FW: 2,
      W: 5,
      WIP: 10,
      S: '1F',
      MOV: '6-6',
      equipment: 'Explosive Warhead',
      special_rules: 'Drone, Fly, Hackable',
    },
    {
      name: 'Mashhit Team',
      faction: 'CL',
      category: 'Drone',
      points: 73,
      CC: 4,
      BS: 3,
      DE: 3,
      FW: 3,
      W: 5,
      WIP: 10,
      S: 2,
      MOV: '6-2',
      equipment: 'QBZ-110 Bullpup, Drone Blade',
      special_rules: 'Drone, Walker, Hackable',
    },

    // Vehicles
    {
      name: 'Ezekiel Light Mech',
      faction: 'CL',
      category: 'Vehicle',
      points: 92,
      CC: 4,
      BS: 3,
      F: 12,
      S: 10,
      R: 10,
      WIP: 7,
      STR: 3,
      MOV: '4-4',
      equipment: '30mm Auto Cannon, Flamer, Mech Foot',
      special_rules: 'Walker, Fanatic, Hackable',
    },
    {
      name: 'Goliath Heavy Mech',
      faction: 'CL',
      category: 'Vehicle',
      points: 105,
      CC: 4,
      BS: 3,
      F: 14,
      S: 14,
      R: 12,
      WIP: 7,
      STR: 6,
      MOV: '4-2',
      equipment: 'Rail Gun, Missile Pod, 30mm Cannon, Flamer',
      special_rules: 'Walker, Fanatic, Hackable',
    },
  ])
}
