import { Knex } from 'knex'

export async function seed(knex: Knex) {
  await knex('units').where({ faction_id: 2 }).del()

  await knex('units').insert([
    // HQ
    {
      name: 'Crusader Clergy Team',
      faction_id: 2,
      type: 'HQ',
      cc: 3,
      bs: 4,
      de: 3,
      fw: 3,
      w: 1,
      wip: 10,
      mov: '4-4',
    },

    // Troops
    {
      name: 'Crusader Rifle Team',
      faction_id: 2,
      type: 'Troop',
      cc: 3,
      bs: 3,
      de: 3,
      fw: 2,
      w: 1,
      wip: 9,
      mov: '4-4',
    },
    {
      name: 'Crusader Specialist Team',
      faction_id: 2,
      type: 'Troop',
      cc: 3,
      bs: 3,
      de: 3,
      fw: 2,
      w: 1,
      wip: 9,
      mov: '4-4',
    },

    // Elites
    {
      name: 'Crusader Zealot Team',
      faction_id: 2,
      type: 'Elite',
      cc: 3,
      bs: 2,
      de: 2,
      fw: 2,
      w: 1,
      wip: 9,
      mov: '6-2',
    },
    {
      name: 'Enhanced Crusader Team',
      faction_id: 2,
      type: 'Elite',
      cc: 4,
      bs: 3,
      de: 3,
      fw: 3,
      w: 2,
      wip: 9,
      mov: '6-2',
    },
    {
      name: 'Assassin Team',
      faction_id: 2,
      type: 'Elite',
      cc: 5,
      bs: 3,
      de: 3,
      fw: 3,
      w: 1,
      wip: 10,
      mov: '6-2',
    },

    // Drones
    {
      name: 'Tarantula Team',
      faction_id: 2,
      type: 'Drone',
      cc: 3,
      bs: 2,
      de: 3,
      fw: 3,
      w: 1,
      wip: 10,
      mov: '4-4',
    },
    {
      name: 'Locust Team',
      faction_id: 2,
      type: 'Drone',
      cc: null,
      bs: null,
      de: 2,
      fw: 2,
      w: 1,
      wip: 10,
      mov: '6-6',
    },
    {
      name: 'Mashhit Team',
      faction_id: 2,
      type: 'Drone',
      cc: 3,
      bs: 3,
      de: 3,
      fw: 3,
      w: 1,
      wip: 10,
      mov: '6-2',
    },

    // Vehicles
    {
      name: 'Ezekiel Light Mech',
      faction_id: 2,
      type: 'Vehicle',
      cc: 3,
      bs: 3,
      s: 3,
      w: 1,
      wip: 7,
      mov: '4-4',
    },
    {
      name: 'Goliath Heavy Mech',
      faction_id: 2,
      type: 'Vehicle',
      cc: 3,
      bs: 3,
      s: 4,
      w: 1,
      wip: 7,
      mov: '4-2',
    },
  ])
}
