import { Knex } from 'knex'

export async function seed(knex: Knex) {
  await knex('unit_options').whereIn('unit_id', knex('units').select('id').where({ faction_id: 1 })).del()
  await knex('units').where({ faction_id: 1 }).del()

  const units = [
    // HQ
    {
      name: 'Marine Command Squad',
      faction_id: 1,
      category: 'HQ',
      base_size: 5,
      max_size: 5,
      cost_per_model: 10,
      cc: 4,
      bs: 4,
      de: 2,
      fw: 1,
      w: 1,
      wip: 10,
      mov: '4-4',
      equipment: 'M-10 Smart Carbine, Grenades, Adaptive Camo',
      special_rules: 'Infantry, Navy',
      options: [
        { name: 'FAC', points: 50 },
        { name: 'Medic', points: 2 },
        { name: 'Hacker', points: 2 },
      ],
    },
    // Troop
    {
      name: 'Marine Rifle Squad',
      faction_id: 1,
      category: 'Troop',
      base_size: 5,
      max_size: 10,
      cost_per_model: 8,
      cc: 3,
      bs: 4,
      de: 2,
      fw: 2,
      w: 1,
      wip: 10,
      mov: '4-4',
      equipment: 'M-10 Smart Carbine, Grenades, Adaptive Camo',
      special_rules: 'Infantry, Navy',
      options: [
        { name: 'LMG', points: 3 },
        { name: 'Medic', points: 2 },
        { name: 'Hacker', points: 2 },
      ],
    },
    {
      name: 'Marine Specialist Team',
      faction_id: 1,
      category: 'Troop',
      base_size: 3,
      max_size: 3,
      cost_per_model: 8,
      cc: 3,
      bs: 4,
      de: 2,
      fw: 1,
      w: 1,
      wip: 9,
      mov: '4-4',
      equipment: 'M-10 Smart Carbine, Grenades, Adaptive Camo',
      special_rules: 'Infantry, Navy',
      options: [
        { name: 'HMG', points: 4 },
        { name: 'Benling', points: 6 },
        { name: 'Guided Mortar', points: 5 },
        { name: 'Smart Sniper Rifle', points: 4 },
      ],
    },
    // Elite
    {
      name: 'Marine Airborne Team',
      faction_id: 1,
      category: 'Elite',
      base_size: 5,
      max_size: 10,
      cost_per_model: 10,
      cc: 4,
      bs: 4,
      de: 3,
      fw: 2,
      w: 1,
      wip: 9,
      mov: '6-2',
      equipment: 'Bonehammer Shotguns, Shitachi, Grenades, Adaptive Camo',
      special_rules: 'Infantry, Navy, Airbourne, Flurry Of Blades (2)',
      options: [{ name: 'Swap Shotguns for SMGs', points: 0 }],
    },
    {
      name: 'Exo-Marine Squad',
      faction_id: 1,
      category: 'Elite',
      base_size: 3,
      max_size: 5,
      cost_per_model: 20,
      cc: 3,
      bs: 4,
      de: 4,
      fw: 2,
      w: 2,
      wip: 9,
      mov: '6-2',
      equipment: 'Light Machine Guns, Infrared Sensors',
      special_rules: 'Infantry, Navy, Hackable',
    },
    {
      name: 'Envoy Ranger Squad',
      faction_id: 1,
      category: 'Elite',
      base_size: 3,
      max_size: 5,
      cost_per_model: 26,
      cc: 4,
      bs: 5,
      de: 3,
      fw: 2,
      w: 1,
      wip: 10,
      mov: '6-2',
      equipment: 'Smart Sniper Rifles, Heavy Pistols, Shitachi, Adaptive Camo, Infra-Red Sensors, Explosive Charges, Targeting Laser',
      special_rules: 'Infantry, Navy, Infiltrators, Ambushers, Flurry Of Blades (3)',
    },
    // Drones
    {
      name: 'Trilobite Scout Drone',
      faction_id: 1,
      category: 'Drone',
      base_size: 3,
      max_size: 6,
      cost_per_model: 8,
      cc: 0,
      bs: 3,
      de: 0,
      fw: 0,
      w: 1,
      wip: 10,
      mov: '6-6',
      equipment: 'Targeting Laser, Infrared Sensors, Adaptive Camo',
      special_rules: 'Drone, Fly, Hackable',
    },
    {
      name: 'Barracuda Attack Drone',
      faction_id: 1,
      category: 'Drone',
      base_size: 3,
      max_size: 6,
      cost_per_model: 13,
      cc: 0,
      bs: 3,
      de: 1,
      fw: 1,
      w: 1,
      wip: 10,
      mov: '6-6',
      equipment: 'M-10 Smart Carbines, Infrared Sensors, Adaptive Camo',
      special_rules: 'Drone, Fly, Hackable',
    },
    {
      name: 'Vanguard Infantry Drone',
      faction_id: 1,
      category: 'Drone',
      base_size: 5,
      max_size: 10,
      cost_per_model: 8,
      cc: 2,
      bs: 3,
      de: 4,
      fw: 1,
      w: 1,
      wip: 10,
      mov: '4-4',
      equipment: 'M-10 Smart Carbines',
      special_rules: 'Drone, Hackable',
    },
    // Vehicles
    {
      name: 'Carrowary Light Support Mech',
      faction_id: 1,
      category: 'Vehicle',
      points: 115,
      cc: 2,
      bs: 4,
      de: 0,
      fw: 3,
      w: 6,
      str: 3,
      wip: 9,
      mov: '6-4',
      equipment: '75mm Cannon, Guided Missile Pod, 25mm Gatling Cannon, Adaptive Camo, Mech Foot',
      special_rules: 'Walker, Navy, Turret, Hackable',
      f: 10,
      s: 10,
      r: 10,
    },
    {
      name: 'Stingray Mech Destroyer',
      faction_id: 1,
      category: 'Vehicle',
      points: 105,
      cc: 0,
      bs: 4,
      de: 0,
      fw: 3,
      w: 4,
      str: 2,
      wip: 9,
      mov: '6-6',
      equipment: 'Rail Gun, Adaptive Camo',
      special_rules: 'Hovercraft, Hackable',
      f: 12,
      s: 10,
      r: 10,
    },
  ]

  for (const unit of units) {
    const { options, ...unitData } = unit
    const [unitId] = await knex('units').insert(unitData)

    if (options && options.length > 0) {
      const optionsWithUnitId = options.map((opt) => ({ ...opt, unit_id: unitId }))
      await knex('unit_options').insert(optionsWithUnitId)
    }
  }
}
