// server/db/seeds/ofn_units.js
export async function seed(knex) {
  // Delete existing OFN units
  await knex('units').where({ faction: 'OFN' }).del()

  await knex('units').insert([
    // HQ
    {
      name: 'Marine Command Team',
      faction: 'OFN',
      category: 'HQ',
      points: 48,
      CC: 3,
      BS: 4,
      DE: 3,
      FW: 3,
      W: 1,
      WIP: 10,
      S: 2,
      MOV: '4-4',
      equipment: 'Standard Issue Rifles',
      special_rules: 'Infantry, Command',
    },

    // Troops
    {
      name: 'Marine Rifle Team',
      faction: 'OFN',
      category: 'Troop',
      points: 44,
      CC: 3,
      BS: 3,
      DE: 3,
      FW: 2,
      W: 1,
      WIP: 9,
      S: 2,
      MOV: '4-4',
      equipment: 'Standard Issue Rifles',
      special_rules: 'Infantry',
    },
    {
      name: 'Marine Specialist Team',
      faction: 'OFN',
      category: 'Troop',
      points: 36,
      CC: 3,
      BS: 3,
      DE: 2,
      FW: 2,
      W: 1,
      WIP: 9,
      S: 2,
      MOV: '4-4',
      equipment: 'Specialist Gear',
      special_rules: 'Infantry, Specialist',
    },

    // Elites
    {
      name: 'Marine Airborne Team',
      faction: 'OFN',
      category: 'Elite',
      points: 48,
      CC: 4,
      BS: 3,
      DE: 3,
      FW: 3,
      W: 1,
      WIP: 10,
      S: 2,
      MOV: '4-4',
      equipment: 'Jump Packs, Rifles',
      special_rules: 'Infantry, Airborne',
    },
    {
      name: 'Exo-Marine Team',
      faction: 'OFN',
      category: 'Elite',
      points: 65,
      CC: 4,
      BS: 4,
      DE: 4,
      FW: 3,
      W: 2, // Power Armour
      WIP: 10,
      S: 3,
      MOV: '4-4',
      equipment: 'Power Armour, Heavy Weapons',
      special_rules: 'Infantry, Elite, Power Armour',
    },
    {
      name: 'Envoy Team',
      faction: 'OFN',
      category: 'Elite',
      points: 80,
      CC: 4,
      BS: 4,
      DE: 4,
      FW: 3,
      W: 1,
      WIP: 10,
      S: 3,
      MOV: '4-4',
      equipment: 'Special Ops Gear',
      special_rules: 'Infantry, Elite, Specialist',
    },

    // Drones
    {
      name: 'Trilobite Team',
      faction: 'OFN',
      category: 'Drone',
      points: 29,
      CC: 3,
      BS: 2,
      DE: 3,
      FW: 3,
      W: 1,
      WIP: 10,
      S: 1,
      MOV: '4-4',
      equipment: 'Drone Weapons',
      special_rules: 'Drone',
    },
    {
      name: 'Barracuda Team',
      faction: 'OFN',
      category: 'Drone',
      points: 37,
      CC: 3,
      BS: 3,
      DE: 3,
      FW: 3,
      W: 1,
      WIP: 10,
      S: 1,
      MOV: '4-4',
      equipment: 'Drone Weapons',
      special_rules: 'Drone',
    },
    {
      name: 'Vanguard Team',
      faction: 'OFN',
      category: 'Drone',
      points: 42,
      CC: 3,
      BS: 3,
      DE: 3,
      FW: 3,
      W: 1,
      WIP: 10,
      S: 1,
      MOV: '4-4',
      equipment: 'Drone Weapons',
      special_rules: 'Drone',
    },
    {
      name: 'Vanguard Specialist Team',
      faction: 'OFN',
      category: 'Drone',
      points: 46,
      CC: 3,
      BS: 3,
      DE: 3,
      FW: 3,
      W: 1,
      WIP: 10,
      S: 1,
      MOV: '4-4',
      equipment: 'Specialist Drone Gear',
      special_rules: 'Drone, Specialist',
    },

    // Vehicles
    {
      name: 'Carrowary Light Support Mech',
      faction: 'OFN',
      category: 'Vehicle',
      points: 115,
      CC: 3,
      BS: 3,
      F: 4,
      S: 4,
      R: 3,
      WIP: 7,
      S: 6,
      STR: 5,
      MOV: '4-4',
      equipment: 'Cannon, Mech Foot',
      special_rules: 'Walker, Fanatic',
      armour: { front: 10, side: 10, rear: 10 },
    },
    {
      name: 'Stingray Mech Destroyer',
      faction: 'OFN',
      category: 'Vehicle',
      points: 105,
      CC: 3,
      BS: 3,
      F: 4,
      S: 3,
      R: 3,
      WIP: 7,
      S: 6,
      STR: 4,
      MOV: '4-4',
      equipment: 'Heavy Cannon, Mech Foot',
      special_rules: 'Walker, Fanatic',
      armour: { front: 10, side: 10, rear: 8 },
    },
  ])
}
